/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutHubsRouteImport } from './routes/_layout/hubs'
import { Route as LayoutIncidentsRouteImport } from './routes/_layout/incidents'
import { Route as LayoutPerformanceRouteImport } from './routes/_layout/performance'
import { Route as LayoutRoutesRouteImport } from './routes/_layout/routes'
import { Route as LayoutSlaRouteImport } from './routes/_layout/sla'
import { Route as LayoutTracabiliteRouteImport } from './routes/_layout/tracabilite'
import { Route as LayoutExpeditionsIndexRouteImport } from './routes/_layout/expeditions/index'
import { Route as LayoutExpeditionsShipmentIdRouteImport } from './routes/_layout/expeditions/$shipmentId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHubsRoute = LayoutHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIncidentsRoute = LayoutIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPerformanceRoute = LayoutPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoutesRoute = LayoutRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSlaRoute = LayoutSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTracabiliteRoute = LayoutTracabiliteRouteImport.update({
  id: '/tracabilite',
  path: '/tracabilite',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpeditionsIndexRoute = LayoutExpeditionsIndexRouteImport.update({
  id: '/expeditions/',
  path: '/expeditions/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpeditionsShipmentIdRoute =
  LayoutExpeditionsShipmentIdRouteImport.update({
    id: '/expeditions/$shipmentId',
    path: '/expeditions/$shipmentId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/hubs': typeof LayoutHubsRoute
  '/incidents': typeof LayoutIncidentsRoute
  '/performance': typeof LayoutPerformanceRoute
  '/routes': typeof LayoutRoutesRoute
  '/sla': typeof LayoutSlaRoute
  '/tracabilite': typeof LayoutTracabiliteRoute
  '/expeditions/$shipmentId': typeof LayoutExpeditionsShipmentIdRoute
  '/expeditions/': typeof LayoutExpeditionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/hubs': typeof LayoutHubsRoute
  '/incidents': typeof LayoutIncidentsRoute
  '/performance': typeof LayoutPerformanceRoute
  '/routes': typeof LayoutRoutesRoute
  '/sla': typeof LayoutSlaRoute
  '/tracabilite': typeof LayoutTracabiliteRoute
  '/': typeof LayoutIndexRoute
  '/expeditions/$shipmentId': typeof LayoutExpeditionsShipmentIdRoute
  '/expeditions': typeof LayoutExpeditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/hubs': typeof LayoutHubsRoute
  '/_layout/incidents': typeof LayoutIncidentsRoute
  '/_layout/performance': typeof LayoutPerformanceRoute
  '/_layout/routes': typeof LayoutRoutesRoute
  '/_layout/sla': typeof LayoutSlaRoute
  '/_layout/tracabilite': typeof LayoutTracabiliteRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/expeditions/$shipmentId': typeof LayoutExpeditionsShipmentIdRoute
  '/_layout/expeditions/': typeof LayoutExpeditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/hubs'
    | '/incidents'
    | '/performance'
    | '/routes'
    | '/sla'
    | '/tracabilite'
    | '/expeditions/$shipmentId'
    | '/expeditions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/hubs'
    | '/incidents'
    | '/performance'
    | '/routes'
    | '/sla'
    | '/tracabilite'
    | '/'
    | '/expeditions/$shipmentId'
    | '/expeditions'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/hubs'
    | '/_layout/incidents'
    | '/_layout/performance'
    | '/_layout/routes'
    | '/_layout/sla'
    | '/_layout/tracabilite'
    | '/_layout/'
    | '/_layout/expeditions/$shipmentId'
    | '/_layout/expeditions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hubs': {
      id: '/_layout/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof LayoutHubsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/incidents': {
      id: '/_layout/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof LayoutIncidentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/performance': {
      id: '/_layout/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof LayoutPerformanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/routes': {
      id: '/_layout/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof LayoutRoutesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sla': {
      id: '/_layout/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof LayoutSlaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tracabilite': {
      id: '/_layout/tracabilite'
      path: '/tracabilite'
      fullPath: '/tracabilite'
      preLoaderRoute: typeof LayoutTracabiliteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expeditions/': {
      id: '/_layout/expeditions/'
      path: '/expeditions'
      fullPath: '/expeditions/'
      preLoaderRoute: typeof LayoutExpeditionsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expeditions/$shipmentId': {
      id: '/_layout/expeditions/$shipmentId'
      path: '/expeditions/$shipmentId'
      fullPath: '/expeditions/$shipmentId'
      preLoaderRoute: typeof LayoutExpeditionsShipmentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutHubsRoute: typeof LayoutHubsRoute
  LayoutIncidentsRoute: typeof LayoutIncidentsRoute
  LayoutPerformanceRoute: typeof LayoutPerformanceRoute
  LayoutRoutesRoute: typeof LayoutRoutesRoute
  LayoutSlaRoute: typeof LayoutSlaRoute
  LayoutTracabiliteRoute: typeof LayoutTracabiliteRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutExpeditionsShipmentIdRoute: typeof LayoutExpeditionsShipmentIdRoute
  LayoutExpeditionsIndexRoute: typeof LayoutExpeditionsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHubsRoute: LayoutHubsRoute,
  LayoutIncidentsRoute: LayoutIncidentsRoute,
  LayoutPerformanceRoute: LayoutPerformanceRoute,
  LayoutRoutesRoute: LayoutRoutesRoute,
  LayoutSlaRoute: LayoutSlaRoute,
  LayoutTracabiliteRoute: LayoutTracabiliteRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutExpeditionsShipmentIdRoute: LayoutExpeditionsShipmentIdRoute,
  LayoutExpeditionsIndexRoute: LayoutExpeditionsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
